### ISSUE TITLE
watch+reload a folder that get destroyed and recreated?

### ISSUE THREAD

**Issue by kevinrenskers** [rabidaudio/swank#15]
I'm trying to find a nice watch+reload dev server to use when I am working on my statically generated website. Swank looks really good, but there is a problem: if you first remove the build folder and then recreate it, you simply get a 404 in your web browser. 

```
swank --watch --path build
```

If the static site generator destroys and recreates the "build" folder, immediately when that folder is deleted, Swank reloads to show a 404 and is then stuck there. Is this a situation that could be improved, or is this simply not a supported workflow?

**Comment by rabidaudio** [comment]
Hey @kevinrenskers, thanks for the report!

I tried to recreate this issue but I wasn't able to. Which operating system are you on? It seems like [chokidar](https://www.npmjs.com/package/chokidar) might have different behavior by platform.

If you can make a test that recreates the issue then that would help a lot.

**Comment by kevinrenskers** [comment]
I'm on macOS. Not sure how I would create such a test - I'm just watching a folder, which gets recreated.

But I ended up using browser-sync, which handles this situation without problem.

**Comment by rabidaudio** [comment]
Nevermind, I think I figured out the problem. Fixed in `v1.4.0`. Thanks for your help!
