### ISSUE TITLE
hostname

### ISSUE THREAD

**Issue by ricardobeat** [rabidaudio/swank#9]
Swank gets the hostname from `os.hostname()` by default instead of `localhost`. For most setups this won't work at all, the hostname does not point at anything.

For example, it tells me to use `http://ml1234:8000`. I can still browse `localhost:8000`, but this causes live-reload to crash with `Error: getaddrinfo ENOTFOUND ml1234`.

**Comment by rabidaudio** [comment]
I went ahead and replaced it with `localhost`. Out of curiosity, which platform are you on?
